Added the use case for predictions
nsaroiu/TTC-Tracker pull request #13
Opened 2023-10-30 20:36 UTC by KuzeyOzturac

2023-10-30 20:53 UTC, Swithord requested changes
missing input data class

2023-11-13 23:18 UTC, nsaroiu requested changes
hey, make sure you address the changes

2023-11-13 23:18 UTC, nsaroiu commented on src/use_case/PredictionsInteractor.java
> +        this.predictionsDataAccessInterface = predictionsDataAccessInterface;
test poopoo peepee

2023-11-13 23:18 UTC, nsaroiu commented on src/use_case/PredictionsOutputData.java
> +    //direction string,
test 2

2023-11-13 23:24 UTC, KuzeyOzturac commented on src/use_case/PredictionsOutputData.java
> +    //direction string,
Change addressed and committed!

2023-11-13 23:25 UTC, nsaroiu reviewed
Thank you for addressing the changes

2023-11-17 17:02 UTC, closed without merging