Stop Details Use Case
nsaroiu/TTC-Tracker pull request #35
Opened 2023-11-18 20:24 UTC by KuzeyOzturac

2023-11-19 22:54 UTC, prash-red requested changes
The overall code looks good. Make an implementation file that implements the actual use-case. Service is supposed to be an interface between the controller and implementation. Look at how I implemented the show_stops use-case.

2023-11-19 22:54 UTC, prash-red commented on backend/src/main/java/com/example/backend/use_case/stop_details/StopDetailsController.java
This file should be moved to interface_adapters.

2023-11-19 22:54 UTC, prash-red commented on backend/src/main/java/com/example/backend/use_case/stop_details/StopDetailsService.java
The service file should be an interface between the controller and the implementation

2023-11-20 21:10 UTC, prash-red reviewed
Looks good !👌

2023-11-20 21:33 UTC, nsaroiu requested changes

2023-11-20 21:33 UTC, nsaroiu commented on backend/src/main/java/com/example/backend/interface_adapters/StopDetailsController.java
> +//    public StopDetailsController(StopDetailsService stopDetailsService){
Remove this comment

2023-11-20 21:33 UTC, nsaroiu commented on backend/src/main/java/com/example/backend/use_case/stop_details/StopDetailsImplementation.java
> +//    public StopDetailsService(StopDataAccessInterface stopDataAccessObject, RouteDataAccessInterface routeDataAccessObject){
Remove this comment

2023-11-20 21:33 UTC, nsaroiu commented on backend/src/main/java/com/example/backend/use_case/stop_details/StopDetailsInputData.java
Why not pass this as a parameter?

2023-11-20 21:33 UTC, nsaroiu commented on backend/src/main/java/com/example/backend/use_case/stop_details/StopDetailsOutputData.java
> +    private HashMap<String, ArrayList<Object>> routeTagsToWrapper;
Return a mapping of Route Tag to a mapping of direction tag to direction name.

2023-11-20 21:33 UTC, nsaroiu commented on backend/src/main/java/com/example/backend/use_case/stop_details/StopDetailsImplementation.java
> +    public StopDetailsOutputData execute(StopDetailsInputData inputData){
Update implementation to reflect changes in the OutputData.

2023-11-20 21:33 UTC, nsaroiu commented on backend/src/main/java/com/example/backend/use_case/stop_details/StopDetailsOutputData.java
> +    public String getName(){return this.stopName;}
Rename to getStopName()

2023-11-20 21:33 UTC, nsaroiu commented on backend/src/main/java/com/example/backend/use_case/stop_details/StopDetailsService.java
> +     * Given an input data, extracts the stopTag and fetches the name of the corresponding stop.
Remove comment

2023-11-20 21:57 UTC, nsaroiu requested changes
Just make sure to change the endpoint, otherwise it is perfect.

2023-11-20 21:57 UTC, nsaroiu commented on backend/src/main/java/com/example/backend/interface_adapters/StopDetailsController.java
> +    @PostMapping("/stopdetails")
change endpoint to "/stop-details"

2023-11-20 21:59 UTC, nsaroiu approved these changes
Looking good, changes address all feedback

2023-11-20 22:04 UTC, prash-red approved these changes
Changes address all feedback given.

2023-11-20 22:04 UTC, merged